version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - ./.:/code
      - ./nginx-config:/etc/nginx/conf.d
    depends_on:
      - web
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
  adminer:
    image: adminer
    restart: always
    ports:
      - "8082:8080"
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0:8000"
    volumes:
      - .:/code
    expose:
      - "8000"
    depends_on:
      - db
