# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-29 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='server',
            field=models.CharField(default=None, max_length=32),
            preserve_default=False,
        ),
    ]
