# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-29 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_account_server'),
    ]

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champion_id', models.IntegerField()),
                ('name', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=255)),
            ],
        ),
    ]
