# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-29 21:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_champion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_id', models.CharField(max_length=32)),
                ('game_id', models.IntegerField()),
                ('queue', models.IntegerField()),
                ('season', models.IntegerField()),
                ('timestamp', models.IntegerField()),
                ('role', models.CharField(max_length=32)),
                ('lane', models.CharField(max_length=32)),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.Champion')),
            ],
        ),
    ]
